services:
  mongo:
    image: mongo
    command: ["mongod", "--port", "9442"]
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - didjo_mongo_db:/data/db

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      - mongo
    ports:
      - "9441:8000"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   env_file: mongo-express.env
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081

volumes:
  didjo_mongo_db: